"""Added relationships between users, devices, and images

Revision ID: 96da62e76eaf
Revises: fc1cee2e16f3
Create Date: 2024-04-28 07:10:47.245615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96da62e76eaf'
down_revision: Union[str, None] = 'fc1cee2e16f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birdimage', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_birdimage_user_id'), 'birdimage', ['user_id'], unique=False)
    op.create_foreign_key(None, 'birdimage', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'birdimage', type_='foreignkey')
    op.drop_index(op.f('ix_birdimage_user_id'), table_name='birdimage')
    op.drop_column('birdimage', 'user_id')
    # ### end Alembic commands ###
