"""maybe final

Revision ID: efd43e4fee02
Revises: 8d552b956f6c
Create Date: 2024-03-29 04:41:00.318811

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'efd43e4fee02'
down_revision: Union[str, None] = '8d552b956f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birdimage', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_birdimage_device_id'), 'birdimage', ['device_id'], unique=False)
    op.drop_constraint('birdimage_user_id_fkey', 'birdimage', type_='foreignkey')
    op.create_foreign_key(None, 'birdimage', 'device', ['device_id'], ['id'])
    op.drop_column('birdimage', 'user_id')
    op.create_index(op.f('ix_device_user_id'), 'device', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'device', ['device_id'])
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'unique_device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unique_device_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(None, 'device', type_='unique')
    op.drop_index(op.f('ix_device_user_id'), table_name='device')
    op.add_column('birdimage', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'birdimage', type_='foreignkey')
    op.create_foreign_key('birdimage_user_id_fkey', 'birdimage', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_birdimage_device_id'), table_name='birdimage')
    op.drop_column('birdimage', 'device_id')
    # ### end Alembic commands ###
