"""maybe final1

Revision ID: fc1cee2e16f3
Revises: efd43e4fee02
Create Date: 2024-03-29 04:45:52.255780

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fc1cee2e16f3'
down_revision: Union[str, None] = 'efd43e4fee02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
